### ISSUE TITLE
Crash when trying to smelt mod items

### ISSUE THREAD

**Issue by Woif1990** [VapourDrive/Alt-F4#2]
Tried to smelt Chaos Ore from Silent's gems, and as soon as I try to put it in the furnace this happens:
http://pastebin.com/Yse9d1yp

Also happens with Thaumcraft's native clusters.

Running 
Alt-F4-1.8.9-0.0.2.4
forge-1.8.9-11.15.0.1697-universal

Edit: Also trying to use alumentium from Thaumcraft broke things as well.
http://pastebin.com/Nz4Yuwp4

Double Edit: Trying to smelt with Coal and make smooth stone crashes as well.
http://pastebin.com/s21vpdNU

**Comment by ColinGBos** [comment]
Can I get your full log?, things don't break for me with any of these items, but there is a chance that the recipe registry copying failed, because it's trying to reference a blank arraylist.

**Comment by Woif1990** [comment]
You mean my full startup log or something else?

**Comment by ColinGBos** [comment]
Yes please, it'll contain information that might tell me why the recipe arraylist is empty

**Comment by Woif1990** [comment]
https://drive.google.com/file/d/0B0mCmvEcGbUUeDRJM20tQ3BRM00/view?usp=sharing
this should be it I think.

**Comment by ColinGBos** [comment]
Sorry, can you test with the latest version http://minecraft.curseforge.com/projects/alt-f4/files/2275418 and then tell me what happens when you try to do the same thing as you did in the initial crash?
As well, tell my if you can see the registered recipes in JEI?
Really I need a log that has information from when you start up a world, as that's when the recipe registry list is filled.

**Comment by Woif1990** [comment]
will do,it will be a little while though. work unfortunately

**Comment by Woif1990** [comment]
Looks like it's all fixed. Possibly had the wrong version on the server as well. So I see everything/nothing crashes me now. Sorry for the hassle!
